Parameters:
  EndpointName:
    Type: String
    Description: Enter the endpoint of Sagemaker model.
  S3BucketName:
    Type: String
    Default: ccemailstore-new
    Description: Enter the bucketname to store emails.
  Domain:
    Type: String
    Default: vijay@assignmentcloud.link
    Description: Enter verified Domain or emailaddress.
Resources:
  SESRule:
    Type: 'AWS::SES::ReceiptRule'
    DependsOn:
      - S3BucketPolicy
    Properties:
      Rule:
        Name: check
        Enabled: true
        Recipients:
          - !Ref Domain
        Actions:
          - S3Action:
              BucketName: !Ref S3Bucket
      RuleSetName: test
  SESRuleSet:
    Type: 'AWS::SES::ReceiptRuleSet'
    Properties:
      RuleSetName: ReceiptRuleSet1
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DependsOn: 
      - LambdaFunction
      - LambdaS3Permission 
    Properties:
      BucketName: !Ref S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Function: !GetAtt LambdaFunction.Arn
  S3BucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: 
        Ref: "S3Bucket"
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "s3:PutObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: "S3Bucket"
                  - "/*"
            Principal: "*"
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    DependsOn:
      - LambdaIamRole
    Properties:
      Handler: lambda_function.lambda_handler
      Role:  !GetAtt LambdaIamRole.Arn
      Layers:
        - arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-numpy:22
      Code:
        S3Bucket: email-cloudformation
        S3Key: scanEmail.zip
      Runtime: python3.8
      Environment:
        Variables:
          ENDPOINT_NAME: !Ref EndpointName
      Timeout: 600
      TracingConfig:
        Mode: Active
  LambdaS3Permission:
    Type: AWS::Lambda::Permission
    DependsOn: 
      - LambdaFunction
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn:
        Fn::Join: 
          - ""
          - 
            - "arn:aws:s3:::"
            - 
              Ref: "S3BucketName"
  LambdaIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: scanEmail-role-new
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /service-role/
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonSESFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
